export const exerciseList = [
  "Abdominal Remador",
  "Agachamento Goblet",
  "Agachamento Livre",
  "Avanço com Halteres",
  "Cadeira Extensora",
  "Cadeira Flexora",
  "Cardio (Corrida, Bicicleta, Elíptico)",
  "Crucifixo (Halteres ou Máquina)",
  "Desenvolvimento de Ombros (Barra ou Halteres)",
  "Desenvolvimento na Máquina",
  "Elevação de Quadril",
  "Elevação Lateral",
  "Elevação Pélvica",
  "Encolhimento de Ombros",
  "Leg Press",
  "Levantamento Terra",
  "Mesa Flexora",
  "Panturrilha em Pé",
  "Panturrilha Sentado",
  "Prancha Isométrica",
  "Puxada Alta",
  "Puxada Frontal",
  "Remada Alta",
  "Remada Cavalinho",
  "Remada Curvada",
  "Remada na Máquina",
  "Remada Serrote",
  "Rosca 21",
  "Rosca Alternada",
  "Rosca Concentrada",
  "Rosca Direta (Barra ou Halteres)",
  "Rosca Inversa",
  "Rosca Martelo",
  "Stiff com Barra",
  "Supino Declinado",
  "Supino Inclinado (Barra ou Halteres)",
  "Supino na Máquina",
  "Supino Reto (Barra ou Halteres)",
  "Tríceps Coice",
  "Tríceps Francês",
  "Tríceps na Polia",
  "Tríceps Testa",
  "Voador Peitoral",
];
