
export const exerciseGifMap: Record<string, string> = {
  // Plano inicial - Mapeado para exrx.net
  "Supino Reto (Barra ou Halteres)": "https://exrx.net/file/clip/PectoralSternal/BarbellBenchPress.gif",
  "Supino Inclinado (Barra ou Halteres)": "https://exrx.net/file/clip/PectoralClavicular/InclineDumbbellPress.gif",
  "Desenvolvimento na Máquina": "https://exrx.net/file/clip/DeltoidAnterior/LeverShoulderPress.gif",
  "Elevação Lateral": "https://exrx.net/file/clip/DeltoidLateral/DumbbellLateralRaise.gif",
  "Puxada Frontal": "https://exrx.net/file/clip/LatissimusDorsi/CBFrontPulldown.gif",
  "Remada Curvada": "https://exrx.net/file/clip/BackGeneral/BentOverBarbellRow.gif",
  "Rosca Direta (Barra ou Halteres)": "https://exrx.net/file/clip/Biceps/BarbellCurl.gif",
  "Rosca Martelo": "https://exrx.net/file/clip/Brachialis/DumbbellHammerCurl.gif",
  "Agachamento Livre": "https://exrx.net/file/clip/Quadriceps/BarbellSquat.gif",
  "Leg Press": "https://exrx.net/file/clip/Quadriceps/Sled45LegPress.gif",
  "Cadeira Extensora": "https://exrx.net/file/clip/Quadriceps/LeverLegExtension.gif",
  "Mesa Flexora": "https://exrx.net/file/clip/Hamstrings/LeverLyingLegCurl.gif",
  "Panturrilha em Pé": "https://exrx.net/file/clip/Gastrocnemius/LeverStandingCalfRaise.gif",
  "Prancha Isométrica": "https://exrx.net/file/clip/RectusAbdominis/FrontPlank.gif",
  "Abdominal Remador": "https://exrx.net/file/clip/HipFlexors/VUp.gif",
  "Levantamento Terra": "https://exrx.net/file/clip/GluteusMaximus/BarbellDeadlift.gif",
  "Remada Cavalinho": "https://exrx.net/file/clip/BackGeneral/LeverT-barRow.gif",
  "Elevação Pélvica": "https://exrx.net/file/clip/GluteusMaximus/BarbellHipThrust.gif",

  // Fallbacks em inglês para outros exercícios (se necessário)
  "barbell bench press": "https://exrx.net/file/clip/PectoralSternal/BarbellBenchPress.gif",
  "dumbbell bench press": "https://exrx.net/file/clip/PectoralSternal/DumbbellBenchPress.gif",
  "incline dumbbell press": "https://exrx.net/file/clip/PectoralClavicular/InclineDumbbellPress.gif",
  "dumbbell flye": "https://exrx.net/file/clip/PectoralSternal/DumbbellFly.gif",
  "dumbbell shoulder press": "https://exrx.net/file/clip/DeltoidAnterior/DumbbellShoulderPress.gif",
  "dumbbell lateral raise": "https://exrx.net/file/clip/DeltoidLateral/DumbbellLateralRaise.gif",
  "bent over row": "https://exrx.net/file/clip/BackGeneral/BentOverBarbellRow.gif",
  "dumbbell row": "https://exrx.net/file/clip/BackGeneral/DumbbellRow.gif",
  "lat pulldown": "https://exrx.net/file/clip/LatissimusDorsi/CBFrontPulldown.gif",
  "barbell curl": "https://exrx.net/file/clip/Biceps/BarbellCurl.gif",
  "hammer curl": "https://exrx.net/file/clip/Brachialis/DumbbellHammerCurl.gif",
  "triceps pushdown": "https://exrx.net/file/clip/Triceps/CBPushdown.gif",
  "lying triceps extension": "https://exrx.net/file/clip/Triceps/BarbellLyingTricepsExtension.gif",
  "dumbbell kickback": "https://exrx.net/file/clip/Triceps/DBKickback.gif",
  "squat": "https://exrx.net/file/clip/Quadriceps/BarbellSquat.gif",
  "lunge": "https://exrx.net/file/clip/Quadriceps/DumbbellLunge.gif",
  "leg press": "https://exrx.net/file/clip/Quadriceps/Sled45LegPress.gif",
  "leg extension": "https://exrx.net/file/clip/Quadriceps/LeverLegExtension.gif",
  "lying leg curl": "https://exrx.net/file/clip/Hamstrings/LeverLyingLegCurl.gif",
  "deadlift": "https://exrx.net/file/clip/GluteusMaximus/BarbellDeadlift.gif",
  "plank": "https://exrx.net/file/clip/RectusAbdominis/FrontPlank.gif",
  "crunches": "https://exrx.net/file/clip/RectusAbdominis/Crunch.gif"
};
