
export const exerciseDescriptions: Record<string, string> = {
  "Abdominal Remador": "Trabalha o abdômen por completo (superior, inferior e oblíquos) e melhora a coordenação, pois exige um movimento sincronizado de tronco e pernas.",
  "Agachamento Goblet": "Fortalece pernas (quadríceps e glúteos) e o core. A posição do peso ajuda a manter a postura correta, sendo ótimo para iniciantes.",
  "Agachamento Livre": "Considerado o 'rei' dos exercícios de perna, trabalha quadríceps, glúteos e posteriores de coxa. Também exige estabilização do core e costas.",
  "Avanço com Halteres": "Excelente para trabalhar cada perna individualmente, focando em quadríceps e glúteos. Melhora o equilíbrio e a estabilidade do quadril.",
  "Cadeira Extensora": "Exercício de isolamento para o quadríceps (a parte da frente da coxa). Ajuda a criar definição e força nesta área específica.",
  "Cadeira Flexora": "Focado nos músculos posteriores da coxa (isquiotibiais). Importante para o equilíbrio muscular das pernas e prevenção de lesões.",
  "Cardio (Corrida, Bicicleta, Elíptico)": "Melhora a saúde do coração e pulmões, aumenta a resistência e auxilia na queima de calorias e gordura corporal.",
  "Crucifixo (Halteres ou Máquina)": "Trabalha a parte externa do peitoral, promovendo a largura do tórax. Exige controle para evitar sobrecarga nos ombros.",
  "Desenvolvimento de Ombros (Barra ou Halteres)": "Principal construtor de massa para os ombros (deltoides). Fortalece a parte frontal e lateral, dando um aspecto mais largo.",
  "Desenvolvimento na Máquina": "Similar ao desenvolvimento com pesos livres, mas oferece mais estabilidade. Ótimo para focar na força dos ombros com segurança.",
  "Elevação de Quadril": "Ativação primária dos glúteos. É um ótimo exercício para fortalecer e dar volume ao bumbum, com menor pressão na coluna.",
  "Elevação Lateral": "Exercício de isolamento para a cabeça lateral do deltoide (ombros), fundamental para criar um aspecto de ombros mais largos e arredondados.",
  "Elevação Pélvica": "Semelhante à elevação de quadril, mas geralmente com maior amplitude. É um poderoso construtor de glúteos e fortalece a região lombar.",
  "Encolhimento de Ombros": "Focado no músculo trapézio, na parte superior das costas e pescoço. Ajuda a construir uma aparência mais forte e densa na região.",
  "Leg Press": "Permite trabalhar as pernas com cargas elevadas e com grande segurança para a coluna. Foca em quadríceps, glúteos e posteriores.",
  "Levantamento Terra": "Exercício composto que trabalha o corpo todo: pernas, glúteos, costas, core e braços. É um dos melhores para ganho de força geral.",
  "Mesa Flexora": "Alternativa à cadeira flexora, também isolando os posteriores da coxa. A posição deitada pode favorecer uma maior contração do músculo.",
  "Panturrilha em Pé": "Trabalha o gastrocnêmio, a cabeça maior do músculo da panturrilha, responsável pelo 'volume' da região.",
  "Panturrilha Sentado": "Foca no músculo sóleo, que fica sob o gastrocnêmio. Essencial para o desenvolvimento completo e força da panturrilha.",
  "Prancha Isométrica": "Fortalece profundamente o core (abdômen, lombar, oblíquos). Melhora a estabilidade da coluna e a postura geral do corpo.",
  "Puxada Alta": "Variação da puxada frontal, focando na parte superior das costas e trapézio. Ajuda a criar densidade e detalhe na parte de cima do dorso.",
  "Puxada Frontal": "Excelente para trabalhar a largura das costas (latíssimo do dorso). É a base para construir costas em formato de 'V'.",
  "Remada Alta": "Trabalha a parte superior das costas e os deltoides (ombros). Ajuda na postura e na criação de um 'miolo' das costas mais forte.",
  "Remada Cavalinho": "Um clássico para densidade das costas. Trabalha o latíssimo do dorso e o meio das costas, permitindo o uso de cargas altas.",
  "Remada Curvada": "Exercício fundamental para as costas, trabalhando latíssimo, romboides e trapézio. Exige um core forte para manter a postura.",
  "Remada na Máquina": "Oferece suporte ao peito, isolando os músculos das costas. Ótima opção para focar na contração muscular com segurança.",
  "Remada Serrote": "Trabalha cada lado das costas individualmente, permitindo maior amplitude e foco no latíssimo do dorso. Melhora a simetria.",
  "Rosca 21": "Um método de alta intensidade para o bíceps, dividindo o movimento em 3 fases de 7 repetições. Promove um grande 'pump' muscular.",
  "Rosca Alternada": "Permite focar em cada bíceps individualmente, garantindo um trabalho equilibrado. Ajuda a corrigir desequilíbrios de força.",
  "Rosca Concentrada": "Exercício de isolamento máximo para o bíceps. Minimiza a ajuda de outros músculos, focando no pico de contração.",
  "Rosca Direta (Barra ou Halteres)": "O principal exercício para construção de massa no bíceps. Pode ser feito com diferentes pegadas para variar o estímulo.",
  "Rosca Inversa": "Fortalece os músculos do antebraço e o músculo braquial (que fica sob o bíceps), contribuindo para um braço mais denso.",
  "Rosca Martelo": "Trabalha o bíceps e o músculo braquiorradial (no antebraço), sendo excelente para aumentar a espessura do braço.",
  "Stiff com Barra": "Focado nos posteriores de coxa e glúteos, com ênfase no alongamento. Essencial para flexibilidade e força nessa cadeia muscular.",
  "Supino Declinado": "Enfatiza a porção inferior do músculo peitoral. Pode ser uma alternativa para quem sente desconforto no ombro com outros supinos.",
  "Supino Inclinado (Barra ou Halteres)": "Direciona o esforço para a parte superior do peitoral (clavicular), uma área muitas vezes difícil de desenvolver.",
  "Supino na Máquina": "Movimento guiado que oferece segurança, ideal para iniciantes ou para aplicar mais carga com menor risco de lesão no peitoral.",
  "Supino Reto (Barra ou Halteres)": "O principal exercício para o desenvolvimento geral do peitoral, trabalhando também ombros e tríceps como secundários.",
  "Tríceps Coice": "Exercício de isolamento para o tríceps, focado na contração de pico. Ideal para ser usado no final do treino para 'lapidar' o músculo.",
  "Tríceps Francês": "Excelente para trabalhar a cabeça longa do tríceps, que contribui muito para o volume do braço. Pode ser feito deitado ou em pé.",
  "Tríceps na Polia": "Um dos exercícios mais populares para o tríceps. Permite variação de pegadores para estimular diferentes porções do músculo.",
  "Tríceps Testa": "Focado em construir massa no tríceps, especialmente a cabeça longa e medial. Exige cuidado com a execução para proteger os cotovelos.",
  "Voador Peitoral": "Também conhecido como 'Peck Deck', é um exercício de isolamento que foca na adução (junção) do peitoral, promovendo o 'miolo' do peito."
};
