import type { Metadata } from "next";
import "./globals.css";
import { MainLayout } from "@/components/main-layout";
import { Toaster } from "@/components/ui/toaster";
import { WorkoutPlanProvider } from "@/contexts/workout-plan-context";

export const metadata: Metadata = {
  title: "Firebase Studio App",
  description: "Generated by Firebase Studio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-body antialiased">
        <WorkoutPlanProvider>
          <MainLayout>{children}</MainLayout>
          <Toaster />
        </WorkoutPlanProvider>
      </body>
    </html>
  );
}
